@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "ru.coderiders.weathergetter.dto.WeatherDto",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_44244634 { 
   	label=coderiders
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_665193335 { 
   	label=weathergetter
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   WeatherDto1858432333[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)WeatherDto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   airTemperature: Double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cloudinessPercent: Integer [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   field: Long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   humidity: Integer [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   iconId: String [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   phenomenonCode: Integer [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   precipitationAmount: Double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   precipitationType: String [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pressure: Integer [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   stormPrediction: Double [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   time: LocalDateTime [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   windSpeed: Double [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ builder(): WeatherDtoBuilder</TD></TR>
<TR><TD ALIGN="LEFT" ># canEqual(other: Object): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml