-- public.task definition

-- Drop table

-- DROP TABLE task;

CREATE TABLE task (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	end_time timestamp NULL,
	start_time timestamp NULL,
	status varchar(255) NULL,
	"type" varchar(255) NULL,
	id_field int8 NULL,
	id_users int8 NULL,
	CONSTRAINT task_pkey PRIMARY KEY (id)
);


-- public.task foreign keys

ALTER TABLE public.task ADD CONSTRAINT fkbted5rjqq27pt6egpko4pojpj FOREIGN KEY (id_field) REFERENCES fields(id);
ALTER TABLE public.task ADD CONSTRAINT fkheem4ukk1mouf65ix45taucdh FOREIGN KEY (id_users) REFERENCES users(id);